version: "3"

services:
    web-mvc:
        image: accounttransaction/web-mvc:latest
        container_name: accounttransaction-web-mvc
        ports:
            - 49156:80
        build:
            context: .
            dockerfile: ./AccountTransaction.WebUI/Dockerfile
        restart: always            
        environment:
            ASPNETCORE_ENVIRONMENT: Docker
            ASPNETCORE_URLS: "http://+:80"
            LC_ALL: "pt_BR.UTF-8"
            LANG: "pt_BR.UTF-8"
        depends_on:
            - api-identity
        networks:
            - backend
    
    accounttransaction-rabbit:
        image: rabbitmq:3-management
        container_name: accounttransaction-rabbit
        ports:
            - 5672:5672
            - 15672:15672
        environment:
            RABBITMQ_DEFAULT_USER: "accounttransaction"
            RABBITMQ_DEFAULT_PASS: "accounttransaction"
        networks:
            - backend

    database-identity:
        image: mcr.microsoft.com/mssql/server:2017-latest
        container_name: accounttransaction-database-identity
        ports:
            - 1433:1433
        expose:
            - 1433
        environment:
            SA_PASSWORD: "MyDB@123"
            ACCEPT_EULA: "Y"
        networks:
            - backend
            
    api-identity:
        image: accounttransaction/api-identity:latest
        container_name: accounttransaction-api-identity
        ports:
            - 5420:80
        build: 
            context: .
            dockerfile: ./AccountTransaction.Identity.API/Dockerfile  
        restart: always
        environment: 
            ASPNETCORE_ENVIRONMENT: Docker
            ASPNETCORE_URLS: http://+:80
            CUSTOMCONNSTR_DefaultConnection: "Server=database-identity;Database=DSUsers;MultipleActiveResultSets=true;User Id=sa;Password=MyDB@123"
            AppSettings__DatabaseType: SqlServer
        depends_on:
            - accounttransaction-rabbit
            - database-identity
        networks:
            - backend

networks:
  backend: