version: "3"

services:   
    web-mvc:
        image: accounttransaction/web-mvc:latest
        container_name: accounttransaction-web-mvc
        ports:
            - 5400:80
        build:
            context: .
            dockerfile: ./web/AccountTransaction.WebUI/Dockerfile
        restart: always            
        environment:
            ASPNETCORE_ENVIRONMENT: Docker
            ASPNETCORE_URLS: "http://+:80"
            LC_ALL: "pt_BR.UTF-8"
            LANG: "pt_BR.UTF-8"
        depends_on:
            - api-identity
        networks:
            - backend
    
    accounttransaction-rabbit:
        image: rabbitmq:3-management
        container_name: accounttransaction-rabbit
        ports:
            - 5672:5672
            - 15672:15672
        environment:
            RABBITMQ_DEFAULT_USER: "accounttransaction"
            RABBITMQ_DEFAULT_PASS: "accounttransaction"
        networks:
            - backend

    database-identity:
        image: mcr.microsoft.com/mssql/server:2017-latest
        container_name: accounttransaction-database-identity
        ports:
            - 1433:1433
        expose:
            - 1433
        environment:
            SA_PASSWORD: "MyDB@123"
            ACCEPT_EULA: "Y"
        networks:
            - backend
            
    api-identity:
        image: accounttransaction/api-identity:latest
        container_name: accounttransaction-api-identity
        ports:
            - 5420:80
        build: 
            context: .
            dockerfile: ./services/Identity/AccountTransaction.Identity.API/Dockerfile  
        restart: always
        environment: 
            ASPNETCORE_ENVIRONMENT: Docker
            ASPNETCORE_URLS: http://+:80
            CUSTOMCONNSTR_DefaultConnection: "Server=accounttransaction-database-identity;Database=DSUsers;MultipleActiveResultSets=true;User Id=sa;Password=MyDB@123"
            AppSettings__DatabaseType: SqlServer
        depends_on:
            - jaeger
            - accounttransaction-rabbit
            - database-identity
        networks:
            - backend

    database-account:
        image: mcr.microsoft.com/mssql/server:2017-latest
        container_name: accounttransaction-database-account
        ports:
            - 1434:1433
        expose:
            - 1434
        environment:
            SA_PASSWORD: "MyDB@123"
            ACCEPT_EULA: "Y"
        networks:
            - backend

    api-account:
        image: accounttransaction/api-account:latest
        container_name: accounttransaction-api-account
        ports:
            - 5440:80
        build: 
            context: .
            dockerfile: ./services/Account/AccountTransaction.Account.API/Dockerfile  
        restart: always
        environment: 
            ASPNETCORE_ENVIRONMENT: Docker
            ASPNETCORE_URLS: http://+:80
            CUSTOMCONNSTR_DefaultConnection: "Server=accounttransaction-database-account;Database=DSAccount;MultipleActiveResultSets=true;User Id=sa;Password=MyDB@123"
            AppSettings__DatabaseType: SqlServer
        depends_on:
            - jaeger
            - accounttransaction-rabbit
            - database-account
        networks:
            - backend

    database-transaction:
        image: mcr.microsoft.com/mssql/server:2017-latest
        container_name: accounttransaction-database-transaction
        ports:
            - 1435:1433
        expose:
            - 1435
        environment:
            SA_PASSWORD: "MyDB@123"
            ACCEPT_EULA: "Y"
        networks:
            - backend

    api-transaction:
        image: accounttransaction/api-transaction:latest
        container_name: accounttransaction-api-transaction
        ports:
            - 5480:80
        build: 
            context: .
            dockerfile: ./services/Transaction/AccountTransaction.Transaction.API/Dockerfile
        restart: always
        environment: 
            ASPNETCORE_ENVIRONMENT: Docker
            ASPNETCORE_URLS: http://+:80
            CUSTOMCONNSTR_DefaultConnection: "Server=accounttransaction-database-transaction;Database=DSTransaction;MultipleActiveResultSets=true;User Id=sa;Password=MyDB@123"
            AppSettings__DatabaseType: SqlServer
        depends_on:
            - jaeger
            - accounttransaction-rabbit
            - database-transaction
        networks:
            - backend
            
    jaeger:
        image: jaegertracing/all-in-one:latest
        container_name: accounttransaction-jaeger
        ports:
            - "5775:5775/udp"
            - "6831:6831/udp"
            - "6832:6832/udp"
            - "5778:5778"
            - "16686:16686"
            - "14268:14268"
            - "9411:9411"
        networks:
            - backend

networks:
  backend: