// <auto-generated />
using System;
using AccountTransaction.Account.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AccountTransaction.Account.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230131214710_update_databasee")]
    partial class update_databasee
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AccountTransaction.Account.API.Models.Cartao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("Ativo")
                        .HasColumnType("int");

                    b.Property<int?>("Bloqueado")
                        .HasColumnType("int");

                    b.Property<int>("CVC")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data_Vencimento")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Limite_Saldo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Limite_Saldo_Disponivel")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Numero_Agencia")
                        .HasColumnType("int");

                    b.Property<long>("Numero_Cartao")
                        .HasColumnType("bigint");

                    b.Property<int>("Numero_Conta")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Numero_Conta", "Numero_Agencia");

                    b.ToTable("Cartao", (string)null);
                });

            modelBuilder.Entity("AccountTransaction.Account.API.Models.Conta", b =>
                {
                    b.Property<int>("Numero_Conta")
                        .HasColumnType("int");

                    b.Property<int>("Numero_Agencia")
                        .HasColumnType("int");

                    b.Property<int?>("Ativa")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Identificador_Titular")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome_Titular")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo_Conta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Numero_Conta", "Numero_Agencia");

                    b.ToTable("Conta", (string)null);
                });

            modelBuilder.Entity("AccountTransaction.Account.API.Models.Cartao", b =>
                {
                    b.HasOne("AccountTransaction.Account.API.Models.Conta", "Conta")
                        .WithMany("Cartoes")
                        .HasForeignKey("Numero_Conta", "Numero_Agencia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conta");
                });

            modelBuilder.Entity("AccountTransaction.Account.API.Models.Conta", b =>
                {
                    b.Navigation("Cartoes");
                });
#pragma warning restore 612, 618
        }
    }
}
